BIGTOP-140. need to workaround HDFS-1943
git-svn-id: https://svn.apache.org/repos/asf/incubator/bigtop/trunk@1187832 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl b/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl
--- a/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl
+++ b/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl
@@ -43,13 +43,30 @@ SLEEP_TIME=5
 
 start() {
   echo -n $"Starting $desc (hadoop-@HADOOP_DAEMON@): "
-  daemon @HADOOP_COMMON_ROOT@/bin/hadoop-daemon.sh --config "@HADOOP_CONF_DIR@" start @HADOOP_DAEMON@ $DAEMON_FLAGS
-  RETVAL=$?
 
   if [ "@HADOOP_DAEMON@" = "datanode" ]; then
+    # The following needs to be removed once HDFS-1943 gets finally put to rest.
+    # The logic of this ugly hack is this: IFF we do NOT have jsvc installed it is
+    # guaranteed that we can NOT be running in a secure mode and thus we need to
+    # workaround HDFS-1943 (start as non-root). As soon as jsvc gets installed
+    # we are assuming a secure installation and starting a data node as root.
+    # This leaves 2 corner cases:
+    #    1. HADOOP_DATANODE_USER being set to root
+    #    2. jsvc is installed but Hadoop is configures to run in an unsecure mode
+    # Both will currently fail
+    if [ -f $HADOOP_HOME/libexec/jsvc.amd64 -o -f $HADOOP_HOME/libexec/jsvc.i386 ] ; then
+       DN_USER=root
+    else
+       DN_USER=$HADOOP_DATANODE_USER
+    fi
+    su -s /bin/bash $DN_USER -c "@HADOOP_COMMON_ROOT@/bin/hadoop-daemon.sh --config '@HADOOP_CONF_DIR@' start @HADOOP_DAEMON@ $DAEMON_FLAGS"
+
     # Some processes are slow to start
     sleep $SLEEP_TIME
     checkstatus
+    RETVAL=$?
+  else
+    daemon @HADOOP_COMMON_ROOT@/bin/hadoop-daemon.sh --config "@HADOOP_CONF_DIR@" start @HADOOP_DAEMON@ $DAEMON_FLAGS
     RETVAL=$?
   fi
 
