Merging the Bigtop 0.2.0 RC code
git-svn-id: https://svn.apache.org/repos/asf/incubator/bigtop/branches/hadoop-0.22@1195290 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl b/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl
--- a/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl
+++ b/bigtop-packages/src/rpm/hadoop/SOURCES/hadoop-init.tmpl
@@ -20,12 +20,19 @@
 # chkconfig: 2345 85 15
 # description: Hadoop @HADOOP_DAEMON@
 
-source /etc/rc.d/init.d/functions
-source /etc/default/hadoop
+. /etc/rc.d/init.d/functions
+. /etc/default/hadoop
 
-source @HADOOP_COMMON_ROOT@/bin/hadoop-config.sh
+# Autodetect JAVA_HOME if not defined
+if [ -e /usr/libexec/bigtop-detect-javahome ]; then
+  . /usr/libexec/bigtop-detect-javahome
+elif [ -e /usr/lib/bigtop-utils/bigtop-detect-javahome ]; then
+  . /usr/lib/bigtop-utils/bigtop-detect-javahome
+fi
+
+. @HADOOP_COMMON_ROOT@/bin/hadoop-config.sh
 # FIXME: this needs to be removed once hadoop-config.sh stop clobbering HADOOP_HOME
-source /etc/default/hadoop
+. /etc/default/hadoop
 
 RETVAL_SUCCESS=0
 
@@ -43,15 +50,30 @@ SLEEP_TIME=5
 
 start() {
   echo -n $"Starting $desc (hadoop-@HADOOP_DAEMON@): "
-  daemon @HADOOP_COMMON_ROOT@/bin/hadoop-daemon.sh --config "@HADOOP_CONF_DIR@" start @HADOOP_DAEMON@ $DAEMON_FLAGS
-  RETVAL=$?
+
+  TARGET_USER_NAME="HADOOP_`echo @HADOOP_DAEMON@ | tr a-z A-Z`_USER"
+  TARGET_USER=$(eval "echo \$$TARGET_USER_NAME")
 
   if [ "@HADOOP_DAEMON@" = "datanode" ]; then
-    # Some processes are slow to start
-    sleep $SLEEP_TIME
-    checkstatus
-    RETVAL=$?
+    # The following needs to be removed once HDFS-1943 gets finally put to rest.
+    # The logic of this ugly hack is this: IFF we do NOT have jsvc installed it is
+    # guaranteed that we can NOT be running in a secure mode and thus we need to
+    # workaround HDFS-1943 (start as non-root). As soon as jsvc gets installed
+    # we are assuming a secure installation and starting a data node as root.
+    # This leaves 2 corner cases:
+    #    1. HADOOP_DATANODE_USER being set to root
+    #    2. jsvc is installed but Hadoop is configures to run in an unsecure mode
+    # Both will currently fail
+    if [ -f $HADOOP_HOME/libexec/jsvc.amd64 -o -f $HADOOP_HOME/libexec/jsvc.i386 ] && [ -n "$HADOOP_SECURE_DN_USER" ]; then
+      TARGET_USER=root
+    fi
   fi
+  su -s /bin/bash $TARGET_USER -c "@HADOOP_COMMON_ROOT@/bin/hadoop-daemon.sh --config '@HADOOP_CONF_DIR@' start @HADOOP_DAEMON@ $DAEMON_FLAGS"
+
+  # Some processes are slow to start
+  sleep $SLEEP_TIME
+  checkstatus
+  RETVAL=$?
 
   [ $RETVAL -eq $RETVAL_SUCCESS ] && touch $LOCKFILE
   return $RETVAL
