BIGTOP-598. missing zookeeper init on debian
git-svn-id: https://svn.apache.org/repos/asf/incubator/bigtop/trunk@1341625 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bigtop-packages/src/deb/zookeeper/zookeeper-server.init b/bigtop-packages/src/deb/zookeeper/zookeeper-server.init
--- a/bigtop-packages/src/deb/zookeeper/zookeeper-server.init
+++ b/bigtop-packages/src/deb/zookeeper/zookeeper-server.init
@@ -165,11 +165,19 @@ case "$1" in
 	    exit 1
 	fi
 	;;
-
+    init)
+        if hadoop_check_pidfile $PID_FILE ; then
+          echo "Error: $DESC is running. Stop it first." >&2
+          exit 1
+        else
+          shift
+          su -s /bin/sh zookeeper -c "zookeeper-server-initialize $*"
+        fi
+	;;
     *)
 	N=/etc/init.d/$NAME
   # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N {start|stop|restart|force-reload|status|force-stop}" >&2
+	echo "Usage: $N {start|stop|restart|force-reload|status|force-stop|init}" >&2
 
 	exit 1
 	;;
