Merging trunk
git-svn-id: https://svn.apache.org/repos/asf/incubator/bigtop/branches/RCs@1244141 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bigtop-packages/src/deb/hbase/hbase.prerm b/bigtop-packages/src/deb/hbase/hbase.prerm
--- a/bigtop-packages/src/deb/hbase/hbase.prerm
+++ b/bigtop-packages/src/deb/hbase/hbase.prerm
@@ -15,42 +15,34 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# preinst script for zookeeper
+# prerm script for hbase 
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <new-preinst> `install'
-#        * <new-preinst> `install' <old-version>
-#        * <new-preinst> `upgrade' <old-version>
-#        * <old-preinst> `abort-upgrade' <new-version>
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    install|upgrade)
-        if ! getent passwd zookeeper >/dev/null; then
-                # Adding system user: zookeeper .
-                adduser \
-                  --system \
-                  --group \
-                  --home /var/zookeeper \
-                  --gecos "ZooKeeper User" \
-                  --shell /bin/false \
-                  zookeeper >/dev/null
-        fi
-	install -d -m 0755 -o zookeeper -g zookeeper /var/log/zookeeper
-        install -d -m 0755 -o zookeeper -g zookeeper /var/lib/zookeeper
+    remove|upgrade|deconfigure)
+      update-alternatives --remove hbase-conf /etc/hbase/conf.dist || :
     ;;
 
-    abort-upgrade)
+    failed-upgrade)
     ;;
 
     *)
-        echo "preinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
@@ -61,3 +53,5 @@ esac
 #DEBHELPER#
 
 exit 0
+
+
diff --git a/bigtop-packages/src/deb/sqoop/sqoop.prerm b/bigtop-packages/src/deb/sqoop/sqoop.prerm
--- a/bigtop-packages/src/deb/sqoop/sqoop.prerm
+++ b/bigtop-packages/src/deb/sqoop/sqoop.prerm
@@ -15,26 +15,43 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# postinst script for zookeeper
-
-zookeeper_pkg_name=zookeeper
+# prerm script for sqoop 
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 case "$1" in
-    configure)
-        # Install config alternatives
-        chown -R zookeeper:zookeeper /var/log/zookeeper
-        update-alternatives  --install /etc/${zookeeper_pkg_name}/conf ${zookeeper_pkg_name}-conf /etc/${zookeeper_pkg_name}/conf.dist 30
+    remove|upgrade|deconfigure)
+      update-alternatives --remove sqoop-conf /etc/sqoop/conf.dist || :
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 #DEBHELPER#
+
+exit 0
+
+
