BIGTOP-397. hbase, sqoop and oozie don't use alternatives for managing configuration
(cherry picked from commit 961474b9609bc8b6279a9b6020742ebafe0d3cab)

git-svn-id: https://svn.apache.org/repos/asf/incubator/bigtop/branches/hadoop-0.23@1242937 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bigtop-packages/src/deb/hbase/hbase.prerm b/bigtop-packages/src/deb/hbase/hbase.prerm
--- a/bigtop-packages/src/deb/hbase/hbase.prerm
+++ b/bigtop-packages/src/deb/hbase/hbase.prerm
@@ -15,41 +15,43 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# postinst script for oozie 
+# prerm script for hbase 
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
 #          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    configure)
-        update-alternatives  --install /etc/oozie/conf oozie-conf /etc/oozie/conf.dist 30 
-        chown -R oozie:oozie /var/lib/oozie /var/log/oozie
-        update-rc.d oozie defaults >/dev/null || exit 1
-        /usr/lib/oozie/bin/oozie-setup.sh -hadoop 0.20.200 /usr/lib/hadoop
+    remove|upgrade|deconfigure)
+      update-alternatives --remove hbase-conf /etc/hbase/conf.dist || :
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
 exit 0
+
 
