BIGTOP-87. The following packages don't remove alternatives: flume, hadoop-pig, hadoop-hive, hadoop-hbase
git-svn-id: https://svn.apache.org/repos/asf/incubator/bigtop/trunk@1166910 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bigtop-packages/src/deb/flume/flume.prerm b/bigtop-packages/src/deb/flume/flume.prerm
--- a/bigtop-packages/src/deb/flume/flume.prerm
+++ b/bigtop-packages/src/deb/flume/flume.prerm
@@ -15,31 +15,34 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# preinst script for hive
+# prerm script for hadoop
 #
 # see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 case "$1" in
-    install|upgrade)
-        if ! getent passwd hive >/dev/null; then
-                # Adding system user: hive.
-                adduser \
-                  --system \
-                  --group \
-                  --home /var/lib/hive \
-                  --gecos "Hive User" \
-                  --shell /bin/false \
-                  hive >/dev/null
-        fi
+    remove|upgrade|deconfigure)
+      update-alternatives --remove flume-conf /etc/flume/conf.empty
     ;;
 
-    abort-upgrade)
+    failed-upgrade)
     ;;
 
     *)
-        echo "preinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
@@ -50,3 +53,5 @@ esac
 #DEBHELPER#
 
 exit 0
+
+
